repos:
  # rstcheck - rst file checker
  - repo: https://github.com/rstcheck/rstcheck
    rev: 445861c31d8134562e723d77115721038de2e687 # frozen: v6.2.0
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        args:
          # ignore some special directives and roles used throughout the docs
          - --ignore-directives
          - prompt
          - code-block
          - tabs
          - --ignore-roles
          - raw-html
          - hblue
          - blue
          - green
          - red
          - purple
          - brown
          - --ignore-messages
          - "Undefined substitution referenced"